/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_alvin_camerasource_NativeClass.h>

JNIEXPORT jstring JNICALL
Java_com_example_alvin_camerasource_NativeClass_getMessageFromJNI
  (JNIEnv env, jclass obj){
  return env->NewStringUTF("Hello C++");
  }
